### PR TITLE
start goreleaser

### LINKED ISSUE #286: Provide binaries with each release
If you would nice if you could provide binaries for various architectures and OSes when doing a release. It would simplify installation and setup for users.

### PR DESCRIPTION
**Pull request by metachris**
## 📝 Summary

Start using https://goreleaser.com to create builds on new tags automatically. 

Closes #286

---

## ✅ I have run these commands

* [x] `make lint`
* [x] `make test-race`
* [x] `go mod tidy`

### CODE REVIEW

**Comment by metachris** [comment]
Can't get it to work, running into one of these errors:

* https://github.com/metachris/mev-boost/runs/8154518346?check_suite_focus=true
* https://github.com/metachris/mev-boost/runs/8154482097?check_suite_focus=true

Would appreciate help if anyone has time and interest

**Comment by franciscodiazydiaz** [comment]
Hey @metachris,

I made some progress on this one, and after some trial and error, it is finally working.

To be able to cross-compile the binaries it is necessary to split the building process into two:
1. Linux and Windows: https://github.com/franciscodiazydiaz/mev-boost/blob/gorelease/.goreleaser-linux_windows.yaml
2. Darwin: https://github.com/franciscodiazydiaz/mev-boost/blob/gorelease/.goreleaser-darwin.yaml

This allows us to either point to the write compiler or use a different image, in the case of Darwin. The building step uses the `skip-publish` argument, as it will be run in the release step.

This release step skips the building and pushes the binaries and checksums to the release page on GitHub.

The workflow is defined here:
https://github.com/franciscodiazydiaz/mev-boost/blob/gorelease/.github/workflows/releaser.yaml

I will be glad to continue working on this if you find it useful.

Note: I got the inspiration from the [Bytebase](https://github.com/bytebase/bytebase) project.

**Comment by metachris** [comment]
@franciscodiazydiaz thank you! checking

**Comment by metachris** [comment]
it works! tested in https://github.com/metachris/mev-boost

**Comment by metachris** [comment]
Huge thanks @franciscodiazydiaz

**Pull request merged**
