### PR TITLE
We have a logo now :)

### PR DESCRIPTION
**Pull request by thegostep**
Feel free to place on readme as wanted.

### CODE REVIEW

**Review by avalonche — APPROVED** [review]

**Comment by lekevicius** [comment]
Oh hi friends @metachris and @thegostep ! 

I'm the designer. Will just comment here. If you'd like to save some bytes here's how you might might start the README. Modified from awesome-mev-boost:

```
<p align="center">
<svg width="100px" height="100px" viewBox="0 0 400 400" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M200 140L80 200L200 260V140Z" fill="#3CC9E9"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M188 362L93.4165 220.125L188 267.417V362Z" fill="#64748B"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M200 140L80 200L200 20V140Z" fill="#30F2E0"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M212 132.584L306.584 179.875L212 38V132.584Z" fill="#94A3B8"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M200 140L320 200L200 260V140Z" fill="#48ABF4"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M200 380L320 200L200 260V380Z" fill="#6469E4"/>
</svg>
</p>
<h2 align="center">mev-boost</h2>
<p align="center">mev-boost allows proof-of-stake Ethereum consensus clients to outsource block construction</p>
</p>
<hr />
```

Maybe you want to skip the tagline or change it. But having a logo be a vector SVG is nice, no need to duplicate "mev-boost" words in logo (h2 is good), and centering looks good.

**Comment by lekevicius** [comment]
Another good feature of SVG: it will look good it both light and dark mode github.

**Comment by lekevicius** [comment]
Oh... it might be that github is blocking inline SVG from github.

You will the SVG logo in the dropbox folder: https://www.dropbox.com/sh/gkzbxxauope2bda/AAByKSO4ulIKzhp2GJy4OX3Ia?dl=0

You might need to host the file somewhere and include it as ...

**Comment by metachris** [comment]
horizontal-transparent
horizontal-transparent

**Comment by metachris** [comment]
horizontal-transparent-slim2

**Comment by metachris** [comment]
horizontal-transparent-slim3

**Comment by metachris** [comment]
horizontal-transparent-slim3

**Pull request merged**
