### PR TITLE
Removed two references to the flashbot relay

### PR DESCRIPTION
**Pull request by fredriksvantes**
## 📝 Summary

Change to README.md which removes two references to the flashbots relay

## ⛱ Motivation and Context

Proposing to do this change to have equal exposure for other relays in the readme

## 📚 References

N/A

---

## ✅ I have run these commands

* [x] `make lint`
* [x] `make test-race`
* [x] `go mod tidy`

### CODE REVIEW

**Comment by fredriksvantes** [comment]
The Flashbots Sepolia relay was missing on https://github.com/eth-educators/ethstaker-guides/ , I made a PR to add this: https://github.com/eth-educators/ethstaker-guides/pull/78

**Review by jtraglia — COMMENTED** [review]
Nice, thanks! There are a few other places that may want to be changed too.

* A reference to the Flashbots' Goerli relay in the contributing guide:

https://github.com/flashbots/mev-boost/blob/a461652bded965ac1a27b3bff043e89ee5586b7c/CONTRIBUTING.md?plain=1#L26

* A reference to the (out-of-date) Flashbots' Kiln relay:

https://github.com/flashbots/mev-boost/blob/a461652bded965ac1a27b3bff043e89ee5586b7c/cmd/test-cli/README.md?plain=1#L67

* Reference to Flashbots' relay source:

https://github.com/flashbots/mev-boost/blob/a461652bded965ac1a27b3bff043e89ee5586b7c/README.md?plain=1#L36

**Comment by fredriksvantes** [comment]
> Nice, thanks! There are a few other places that may want to be changed too.
> 
>     * A reference to the Flashbots' Goerli relay in the contributing guide:
> 
> 
> https://github.com/flashbots/mev-boost/blob/a461652bded965ac1a27b3bff043e89ee5586b7c/CONTRIBUTING.md?plain=1#L26
> 
>     * A reference to the (out-of-date) Flashbots' Kiln relay:
> 
> 
> https://github.com/flashbots/mev-boost/blob/a461652bded965ac1a27b3bff043e89ee5586b7c/cmd/test-cli/README.md?plain=1#L67
> 
>     * Reference to Flashbots' relay source:
> 
> 
> https://github.com/flashbots/mev-boost/blob/a461652bded965ac1a27b3bff043e89ee5586b7c/README.md?plain=1#L36

Thanks, I made some additional cleanup based on that!

**Review by jtraglia — APPROVED** [review]
LGTM 🥇

**Review by metachris — APPROVED** [review]

**Pull request merged**
