### PR TITLE
accept gzip encoding

### PR DESCRIPTION
**Pull request by dmarzzz**
## 📝 Summary

From a discussion with @zeroecco on how to lower bandwidth on the blocknative relay we came to the idea that we could utilize well known compression like gzip, but only if requests coming from mev-boost specified that.

Minimum transmittable unit is 1500 Bytes total w/ 1250 Bytes realistically usable and a block is around ~12KB, gzip will compress ~60% to ~6Kb which would be a packet reduction from 10 to 5 for the total packet train. This also reduces time to last packet and bandwidth, which could be 1 - 5ms based on response time at this size.

If a system doesn't have this enabled the content-encoding will simply be ignored.
On top of that, this improvement will really only be visible for GetPayload response.

To benefit from this in your relay or other components make sure you configure your reverse proxy [HA Proxy, NGINX, etc] to support gzip!

## ⛱ Motivation and Context

I want to go fast

## 📚 References

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding

https://www.rfc-editor.org/rfc/rfc2616#section-3.5

## ✅ I have run these commands

* [x] `make lint`
* [x] `make test-race`
* [x] `go mod tidy`

### CODE REVIEW

**Comment by metachris** [comment]
Could you add a little bit of context please?

**Comment by zeroecco** [comment]
Internally our testing did show a time to last packet reduction in deliveries of blocks of roughly 1-5ms depending on the block size and the resources of the validator. 

Additionally this change can lead to more time for validators to propose on chain and thereby potentially lead fewer missing proposals though more efficient packet transport over the wider internet.

**Comment by dmarzzz** [comment]
added some more context @metachris , didn't realize drafts showed up in public repos whoops!

**Comment by metachris** [comment]
Thanks. I suppose you'd still need to add gzip decoding into the request processing? Like outlined here: https://stackoverflow.com/a/13131806

**Comment by dmarzzz** [comment]
Awesome good fix! I added a note to the PR as well that for relays and others to enable this make sure you configure your reverse proxy [HA Proxy, NGINX, etc] to support gzip!

**Comment by dmarzzz** [comment]
The test that lint is tripping up on works for me locally 🤔

**Comment by metachris** [comment]
I think the test is because of an older staticcheck version, will push a PR

**Comment by metachris** [comment]
https://github.com/flashbots/mev-boost/pull/374

**Comment by metachris** [comment]
@dmarzzz could you add a test where the mockserver returns a gzipped response?

**Review by jtraglia — APPROVED** [review]
LGTM. Nice addition. Thanks!

**Comment by metachris** [comment]
Added a test for the gzip response: https://github.com/dmarzzz/mev-boost/pull/1 (needs to be merged by @dmarzzz into his repo to update this PR)

**Comment by dmarzzz** [comment]
@metachris thanks appreciate it, wasn't able to get to it till this weekend. When I merged it auto dismissed @jtraglia review

**Review by jtraglia — APPROVED** [review]
No worries. Thanks for the extra test.

**Pull request merged**
